# Problem Statement

In today's competitive business environment, startups must decide how to allocate their financial resources among key areas such as Research and Development (R&D), Administration, and Marketing. Making the right investment decisions is essential for improving profitability and ensuring long-term business growth.

However, many companies invest significant amounts of money without a clear understanding of how these investments influence their future profits. As a result, inefficient budget allocation can reduce competitiveness and limit financial performance.

To address this issue, a predictive model can be developed to estimate a startup's profit based on its investment in different business areas and the state where it operates. Such a model provides valuable support for strategic planning and financial decision-making.

This project uses Multiple Linear Regression to predict the profit of startups because the target variable depends on several independent variables simultaneously.

### 0- Imports

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### 1- DataSet Import

In [5]:
dataset = pd.read_csv("datasets/50_Startups.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

### 2- Dataset Exploration

In [6]:
dataset.head(15)

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94
5,131876.90,99814.71,362861.36,New York,156991.12
6,134615.46,147198.87,127716.82,California,156122.51
7,130298.13,145530.06,323876.68,Florida,155752.60
8,120542.52,148718.95,311613.29,New York,152211.77
9,123334.88,108679.17,304981.62,California,149759.96


### 4- Encoding Categorical Data


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [8]:
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(sparse_output=False), [3])
    ],
    remainder='passthrough'
)


X = ct.fit_transform(X)

X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

### 4- Avoiding Multicollinearity by Dropping One Dummy Variable

In [9]:
X = X[:, 1:]
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

### 6- Train-Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size = 0.20,
    random_state = 0,
    shuffle = True
)

In [12]:
X_test

array([[1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [13]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

### 7- Building the Optimal Multiple Linear Regression Model Using Backward Elimination

In [14]:
import statsmodels.api as sm

In [1]:
import numpy as np
import statsmodels.api as sm

# Add a column of ones (intercept)
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)


def backward_elimination(X, y, significance_level=0.05):

    # Convert to NumPy arrays
    X = np.asarray(X, dtype=float)
    y = np.asarray(y, dtype=float)

    # Store the current column indices
    columns = list(range(X.shape[1]))

    while True:

        # Build the regression model
        model = sm.OLS(y, X).fit()

        # Get the highest p-value
        max_p_value = max(model.pvalues)

        # If the highest p-value exceeds the significance level
        if max_p_value > significance_level:

            # Index of the least significant variable
            remove_index = model.pvalues.argmax()

            # Remove the corresponding column
            X = np.delete(X, remove_index, axis=1)

            # Remove the stored column index
            columns.pop(remove_index)
        else:
            break

    return X, model, columns


# Train the final model
X_train_final, model, columns = backward_elimination(X_train, y_train)

# Keep the same columns in the test set
X_test_final = X_test[:, columns]

# Make predictions
y_pred = model.predict(X_test_final)

NameError: name 'X_train' is not defined

### 8- Model Evaluation

In [25]:
y_pred

array([104667.27805997859, 134150.8341057847, 135207.80019516923,
       72170.54428855634, 179090.58602508352, 109824.77386586338,
       65644.27773756775, 100481.43277138655, 111431.75202432103,
       169438.148435391], dtype=object)

In [26]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])