### 1. Importar librerias requeridas.

In [3]:
# Importamos las librerias utilizadas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 2. Lectura de datos CSV.

In [4]:
# Leemos los dos archivos CSV
dataset = pd.read_csv("datasets/Data.csv") # DS DataFrame

### 3. Expororacion de dataset.

In [30]:
# Exploramos filas del conjunto de noticias verdaderas
dataset 

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [58]:
X = dataset.iloc[:, :-1].values # iloc Recorta las posiciones indicadas [filas | columnas] y los convierte en un array con .values
y = dataset.iloc[:, 3].values
print("Data X: ", X)
print("Data y: ",y)

Data X:  [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Data y:  ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### 4. Tratamientos de los NAs.

In [35]:
from sklearn.impute import SimpleImputer

In [59]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer = imputer.fit(X[:, 1:3]) # Aprende y guarda los parámetros necesarios para trabajar después.
X[:, 1:3] = imputer.transform(X[:, 1:3]) # Usa lo aprendido para reemplazar los NaN.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### 5. Datos categoricos.

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [64]:
# Indicamos que aplique OneHotEncoder a la columna 0 
# 'remainder="passthrough"' asegura que el resto de las columnas no se modifiquen
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])], 
    remainder='passthrough'
)

# Ajustamos y transformamos la matriz X, convirtiéndola directamente a un array de NumPy
X = ct.fit_transform(X)

# Creamos el codificador para la variable dependiente
labelencoder_y = LabelEncoder()

# Ajustamos y transformamos la variable y
y = labelencoder_y.fit_transform(y)

print("Data X:", X)
print("Data y:", y)


Data X: [[1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
Data y: [0 1 0 0 1 1 0 1 0 1]


### 6. Dividir dataset en dataset para entrenamiento y dataset para test.

In [1]:
from sklearn.model_selection import train_test_split


In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size=0.20,
    random_state=42,
    shuffle=True
)

NameError: name 'train_test_split' is not defined

### 7. Escalar datos

In [72]:
from sklearn.preprocessing import StandardScaler


In [73]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)